# Generated by Django 4.2.2 on 2024-03-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cotegory',
            new_name='category',
        ),
    ]
