# Generated by Django 4.2.2 on 2024-03-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_rename_cotegory_payment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('食費', '食費'), ('日用品', '日用品'), ('交通費', '交通費'), ('趣味・娯楽', '趣味・娯楽'), ('交際費', '交際費'), ('衣服・美容', '衣服・美容'), ('水道・光熱費', '水道・光熱費'), ('家賃', '家賃'), ('医療・健康', '医療・健康'), ('通信費', '通信費'), ('保険', '保険'), ('その他', 'その他')], max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kinds',
            field=models.CharField(choices=[('消費', '消費'), ('浪費', '浪費'), ('投資', '投資')], max_length=20, verbose_name='支出分類'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='memo',
            field=models.CharField(max_length=300, verbose_name='メモ'),
        ),
    ]
