# Generated by Django 4.2.2 on 2024-03-26 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0003_alter_payment_amount_alter_payment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額'),
        ),
    ]
